SumoLogic/tailing-sidecar

operator/handler/config.go
operator/handler/handler.go
operator/handler/handler_test.go
operator/handler/testdata/patch_remove_tailing_sidecar.json

- Remove all sidecars when annotation is empty
- Remove not used volumes created for tailing sidecars

Fix removing tailing sidecars

---

sidecar/README.md
sidecar/examples/pod_with_tailing_sidecars.yaml

doc,examples: update sidecar image in examples

---

dev/releasing.md
helm/tailing-sidecar-operator/Chart.yaml
helm/tailing-sidecar-operator/values.yaml

- Set proper versions for Helm chart and images
- Update release instruction to not forget about changing version in release PR

Set proper versions for Helm chart and images

---

helm/tailing-sidecar-operator/templates/_operator-webhook-with-cert-manager.tpl
helm/tailing-sidecar-operator/templates/_operator-webhook.tpl
helm/tailing-sidecar-operator/values.yaml

- failurePolicy,
- reinvocationPolicy
- objectSelector
- namespaceSelector
Fixes #50

chart: expose webhook configuration

---

operator/Makefile
operator/README.md
operator/handler/handler.go
operator/handler/handler_test.go
operator/handler/testdata/patch_update_1_tailing_sidecar.json
operator/handler/testdata/patch_with_2_tailing_sidecars.json
operator/handler/testdata/patch_with_3_tailing_sidecars.json
operator/handler/testdata/patch_with_4_named_not_named_tailing_sidecars.json
operator/tests/test.sh

Change prefix for default tailing sidecar container name to taling-sidecar-

---

operator/Makefile
operator/README.md
operator/docs/configuration.md
operator/examples/daemonset_with_annotations.yaml
operator/examples/deployment_with_annotations.yaml
operator/examples/deployment_with_annotations_update.yaml
operator/examples/pod_with_annotations.yaml
operator/examples/pod_with_annotations_update.yaml
operator/examples/statefulset_with_annotations.yaml
operator/tests/test.sh

New docs, examples and tests will be added when new form of CRD will be implemented and ready to use.
Related to #55

docs,examples,tests: remove examples with configuration in CRD

---

helm/tailing-sidecar-operator/templates/resources.yaml
operator/api/v1/tailingsidecar_types.go
operator/config/crd/bases/tailing-sidecar.sumologic.com_tailingsidecars.yaml
operator/config/samples/tailing-sidecar_v1_tailingsidecar.yaml
operator/handler/config.go
operator/handler/handler.go
operator/handler/handler_test.go

Related to #55 
In separated pull request there will change for type for volumeMount from `string` to `volumeMount`.

crd: rename volume to volumeMount in CRD definition

---

.github/workflows/pull_requests.yml
helm/tailing-sidecar-operator/templates/resources.yaml
operator/Makefile
operator/config/default/manager_webhook_patch.yaml

Sometimes operator was not ready to handle requests. In my tests operator needs about 84s to be ready.

Add startupProbe and livenessProbe for webhook server

---

helm/tailing-sidecar-operator/Chart.yaml

Some useful changes were introduced after the last release:
https://github.com/SumoLogic/tailing-sidecar/compare/release-v0.3...main

Prepare v0.4.0

---

operator/go.mod
operator/handler/handler.go
operator/handler/handler_test.go
operator/handler/testdata/patch_update_1_tailing_sidecar.json
operator/handler/testdata/patch_with_2_tailing_sidecars.json
operator/handler/testdata/patch_with_2_tailing_sidecars_different_namespace.json
operator/handler/testdata/patch_with_3_named_not_named_tailing_sidecars.json
operator/handler/testdata/patch_with_3_named_tailing_sidecars.json
operator/handler/testdata/patch_with_3_tailing_sidecars.json
operator/handler/testdata/patch_with_3_tailing_sidecars_raw_and_predefined.json

feat!: replace hostPath volume added to tailing sidecars with emptyDir

---

helm/tailing-sidecar-operator/Chart.yaml
operator/docs/configuration.md

https://github.com/SumoLogic/tailing-sidecar/compare/release-v0.4...952c491118f8cd54e9034b1eb218232065999b37

Prepare v0.5.0

---

.github/workflows/pull_requests.yml
helm/tailing-sidecar-operator/templates/resources.yaml
helm/tailing-sidecar-operator/values.yaml

manual backport of https://github.com/SumoLogic/tailing-sidecar/pull/161

feat: kube-rbac-proxy image configurable in values.yaml

---

helm/tailing-sidecar-operator/Chart.yaml
helm/tailing-sidecar-operator/values.yaml

Changes https://github.com/SumoLogic/tailing-sidecar/compare/ea4c339a7bfa883fd7f1f3f8f444d542fc626c4d...ae7f0a5ccdb9a313b7e2d02b2bc85e0845fd7d0d

Prepare v0.3.1

---

.github/workflows/pull_requests.yml

- update k3d-action to 1.5.0, changes in k3d 1.5.0: https://github.com/AbsaOSS/k3d-action/releases/tag/v1.5.0
- change ubuntu version to 20.04 in jobs with k3d
related to #179

update k3d-action to 1.5.0 & change ubuntu version

---

.github/workflows/pull_requests.yml

Fixes #179
Changes in k3d-action 1.5.0: https://github.com/AbsaOSS/k3d-action/releases/tag/v1.5.0

chore: update k3d-action to 1.5.0

---

helm/tailing-sidecar-operator/Chart.yaml
helm/tailing-sidecar-operator/values.yaml

Changes: https://github.com/SumoLogic/tailing-sidecar/compare/v0.3.2...release-v0.3

release: Prepare v0.3.3

---

.github/workflows/dev_builds.yml

chore(ci): build dev images for release-vx.y

---

operator/handler/handler.go
operator/handler/testdata/patch_update_1_tailing_sidecar.json
operator/handler/testdata/patch_with_2_tailing_sidecars.json
operator/handler/testdata/patch_with_3_named_tailing_sidecars.json
operator/handler/testdata/patch_with_3_tailing_sidecars.json
operator/handler/testdata/patch_with_4_named_not_named_tailing_sidecars.json

feat: enable privileged mode for container

---

.github/workflows/dev_builds.yml

feat: build dev images for release-vx.y

---

helm/tailing-sidecar-operator/templates/scc.yaml
helm/tailing-sidecar-operator/values.yaml

feat: add scc configuration

---

helm/tailing-sidecar-operator/Chart.yaml
helm/tailing-sidecar-operator/values.yaml

https://github.com/SumoLogic/tailing-sidecar/compare/v0.3.3...release-v0.3?expand=1

chore: prepare release v0.3.4

---

dev/releasing.md

chore: update releasing instruction

---

.github/workflows/release_builds.yml
operator/Dockerfile
operator/Makefile

fix https://github.com/SumoLogic/tailing-sidecar/issues/400

operator images support multi platforms

---

.github/workflows/dev_builds.yml
sidecar/Makefile

it works well in my fork repo actions ci: https://github.com/JaredTan95/tailing-sidecar/actions/runs/3541915453/jobs/5946774315

support tailing-sidecar multi-arch image build 

---

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml

Now this should resolve the building issues
- using `make build-push-multiplatform`
- with `TAG` in sidecar direcgtory
- with `IMG` in operator directory
- using it for both dev and latest images

chore: fix building main images

---

CHANGELOG.md
helm/tailing-sidecar-operator/Chart.yaml

chore: prepare v0.5.6 release

---

.github/workflows/pull_requests.yml

https://github.com/AbsaOSS/k3d-action/releases/

chore: update AbsaOSS/k3d-action from 1.5.0 to 2.1.0

---

.github/workflows/pull_requests.yml
operator/Makefile
vagrant/provision.sh

This should make `k3d image import` less flaky

build(deps): bump AbsaOSS/k3d-action to 2.4.0

---

CHANGELOG.md
helm/tailing-sidecar-operator/Chart.yaml

chore: prepare release v0.13.0

---

sidecar/fluentbit/Dockerfile.ubi

Update Base Image in order to fix vulnerabilities

chore(sidecar): update Fluent Bit UBI image to 3.0.7

---

CHANGELOG.md

chore: Update changelog 0.16.0

---

CHANGELOG.md

chore: Changelog updates for 0.16.0
