SumoLogic/tailing-sidecar

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml

- Authentication to Github container registry requires personal access token, see: https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages#authenticating-to-github-packages
-  Github container registry can’t accept App tokens, see [this](https://github.community/t/how-to-use-installation-access-token-in-ghcr-io-authorization/130666) discussion

ci: use Personal Access Token to login to Github container registry

---

ci/push-helm-chart.sh

```
--always
Show uniquely abbreviated commit object as fallback.
```

ci: add --always to git describe command to set version when there is no tag

---

.github/workflows/pull_requests.yml
helm/tailing-sidecar-operator/README.md
helm/tailing-sidecar-operator/templates/_operator-webhook-with-cert-manager.tpl
helm/tailing-sidecar-operator/templates/_operator-webhook.tpl
helm/tailing-sidecar-operator/templates/resources.yaml
helm/tailing-sidecar-operator/values.yaml
helm/tests/values.withCertManager.yaml

Added chart property `useCertManager` which is `false` by default, but when changed to `true` it makes it possible to use `cert-manager` if you have it in your cluster.
@sumo-drosiek mentioned that the Telegraf chart's property to use `cert-manager` is called [certManager.enable](https://github.com/influxdata/helm-charts/blob/046d1691553807922ee01fd525f3b1c4efdf0e96/charts/telegraf-operator/values.yaml#L21) and there's value in keeping things consistent, but I don't really like the name (it should be `enabled` and not `enable` anyway). Please give your opinions on the property name.

chart: Make cert-manager optional

---

ci/push-helm-chart.sh

Reverts SumoLogic/tailing-sidecar#91
helm package requires semantic versioning
```
export VERSION="$(git describe --tags --abbrev=40 --always)"
%  helm package helm/tailing-sidecar-operator --dependency-update --version="${VERSION}" --app-version="${VERSION}" --destination test
Error: Invalid Semantic Version
```

Revert "ci: add --always to git describe command to set version when there is no tag"

---

helm/tailing-sidecar-operator/values.yaml

Proper repository for sidecar image is `ghcr.io/sumologic/tailing-sidecar`
https://github.com/orgs/SumoLogic/packages/container/package/tailing-sidecar

chart: fix sidecar image repository

---

helm/tailing-sidecar-operator/templates/_helpers.tpl
helm/tailing-sidecar-operator/templates/_operator-webhook-with-cert-manager.tpl
helm/tailing-sidecar-operator/templates/_operator-webhook.tpl
helm/tailing-sidecar-operator/templates/resources.yaml

According to [Helm Best Practices](https://helm.sh/docs/chart_best_practices/templates/#names-of-defined-templates),
"all defined template names should be namespaced"
because they are globally accessible.

refactor: chart: Rename defined templates' namespace

---

dev/releasing.md
helm/tailing-sidecar-operator/templates/resources.yaml
helm/tailing-sidecar-operator/values.yaml

There will be no need to remember about changing image tags when new release is created.
Fixes #97

Set default tag for container images to .Chart.AppVersion

---

operator/handler/handler.go
operator/handler/handler_test.go
operator/handler/testdata/patch_update_1_tailing_sidecar.json
operator/handler/testdata/patch_with_2_tailing_sidecars.json
operator/handler/testdata/patch_with_3_named_tailing_sidecars.json
operator/handler/testdata/patch_with_3_tailing_sidecars.json
operator/handler/testdata/patch_with_4_named_not_named_tailing_sidecars.json
sidecar/README.md
sidecar/examples/pod_with_tailing_sidecars.yaml

Change prefix for tailing sidecar volume name to `volume-sidecar-` to keep the same style as in naming sidecar container

Change prefix for tailing sidecar volume name to volume-sidecar-

---

.github/workflows/pull_requests.yml

- remove redundant job to build sidecar image, `build` target is included in `make all` for sidecar and it is run  [here](https://github.com/SumoLogic/tailing-sidecar/blob/5914e56cf04792193ef2dbe9b38f609d051c31eb/.github/workflows/pull_requests.yml#L87), [here](https://github.com/SumoLogic/tailing-sidecar/blob/5914e56cf04792193ef2dbe9b38f609d051c31eb/.github/workflows/pull_requests.yml#L133), [here](https://github.com/SumoLogic/tailing-sidecar/blob/5914e56cf04792193ef2dbe9b38f609d051c31eb/.github/workflows/pull_requests.yml#L181)
- remove redundant job to build tailing sidecar operator image , `docker-build` target is included in `make all` for operator and it is run [here](https://github.com/SumoLogic/tailing-sidecar/blob/5914e56cf04792193ef2dbe9b38f609d051c31eb/.github/workflows/pull_req …

Changes in ci jobs running for pull requests

---

helm/tailing-sidecar-operator/templates/_operator-webhook-with-cert-manager.tpl
helm/tailing-sidecar-operator/templates/_operator-webhook.tpl
operator/config/webhook/manifests.yaml
operator/handler/handler.go

Trying to change volumeMount type from string to
VolumeMount from k8s.io/api/core/v1 observed that
when Pod is modified through kubectl apply --force deletion hangs
Related to #55 and #119

operator: add explicit non blocking handling of Pod deletion

---

.github/workflows/pull_requests.yml
operator/Makefile
operator/tests/functions.sh
operator/tests/test-update.sh
operator/tests/test.sh

Testes with following script:
```
#/bin/bash
make deploy
make deploy-examples
make deploy-example-with-crd
sleep 5
make test-examples
make deploy-examples-update
make test-examples-update
```
with `kubectl wait` following error occured:
```
Error from server (NotFound): pods "pod-with-annotations-crd" not found
Makefile:108: recipe for target 'test-examples' failed
make: *** [test-examples] Error 1
```
but Pod was created in a second

Add tests for update of resources modified by operator

---

helm/tailing-sidecar-operator/templates/resources.yaml
operator/config/default/manager_webhook_patch.yaml
operator/handler/handler.go

Proper json request should have appropriate HTTP header:
```
Content-Type: application/json
Accept: application/json
```
this eliminates following error in operator logs: `2021-04-06T10:59:12.161Z        ERROR   controller-runtime.webhook.webhooks     unable to process a request with an unknown content type        {"webhook": "/add-tailing-sidecars-v1-pod", "content type": "", "error": "contentType=, expected application/json"}`
Add better handling for  startupProbe and livenessProbe in operator code to eliminate this errror:
`2021-04-06T11:23:46.412Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/add-tailing-sidecars-v1-pod", "code": 400, "reason": "", "UID": "", "allowed": false}`

Better handling for startupProbe and livenessProbe

---

operator/Dockerfile.ubi
operator/Makefile

example command to build image:
```bash
make docker-build-ubi IMG=ghcr.io/kkujawa-sumo/tailing-sidecar-operator-ubi:test VERSION=0.3.1 RELEASE_NUMBER=6
```

feat: add Dockerfile and Makefile target to build UBI based container image

---

operator/Dockerfile.ubi
sidecar/Dockerfile.ubi
sidecar/Makefile

example command to build image: 
```bash
make build-ubi TAG=ghcr.io/kkujawa-sumo/tailing-sidecar-ubi:test VERSION=0.3.1 RELEASE_NUMBER=6
```

feat: add Dockerfile and Makefile target to build UBI based sidecar container image

---

.github/workflows/pull_requests.yml

There is no purpose in testing with Go versions other than the one specified in the Dockerfile, which should be the latest stable Golang version.

ci: use only latest Golang version

---

CHANGELOG.md
helm/tailing-sidecar-operator/values.yaml
operator/config/default/manager_auth_proxy_patch.yaml

- chore: upgrade kube-rbac-proxy from 0.5.0 to 0.11.0
- chore: change container repository for kube-rbac-proxy to `quay.io/brancz/kube-rbac-proxy`
which is the official container repository for https://github.com/brancz/kube-rbac-proxy
see also: https://github.com/brancz/kube-rbac-proxy/blob/4f59920d1164aa804d94f5207451b0450831556b/Makefile#L13
related to #170

chore: upgrade kube-rbac-proxy from 0.5.0 to 0.11.0

---

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml

set go version to 1.17, 
fixes following error: https://github.com/SumoLogic/tailing-sidecar/runs/5249530879?check_suite_focus=true

fix: github action for builing dev and releases images

---

helm/tailing-sidecar-operator/templates/resources.yaml

This fixes the error "error retrieving resource lock \<namespace\>/7b555970.sumologic.com: leases.coordination.k8s.io "7b555970.sumologic.com" is forbidden"
Fixes #168

fix(chart): add permissions for leases

---

helm/tailing-sidecar-operator/templates/scc.yaml
helm/tailing-sidecar-operator/values.yaml

feat: add scc configuration

---

sidecar/Dockerfile

This addresses https://www.cve.org/CVERecord?id=CVE-2022-37434 and https://www.cve.org/CVERecord?id=CVE-2021-3999, should be removed after the next Fluent-Bit version is released.

chore: upgrade libc and zlib in the Dockerfile

---

.github/workflows/pull_requests.yml

Fixes: https://github.com/SumoLogic/tailing-sidecar/actions/runs/3358738681/jobs/5566068791
```
ERROR:  Error installing mdl:
The last version of mdl (>= 0) to support your Ruby & RubyGems was 0.11.0. Try installing it with `gem install mdl -v 0.11.0`
mdl requires Ruby version >= 2.7. The current ruby version is 2.6.10.210.
```

chore: fix mdl check

---

CHANGELOG.md
helm/tailing-sidecar-operator/templates/_operator-webhook-with-cert-manager.tpl
helm/tailing-sidecar-operator/templates/_operator-webhook.tpl
operator/config/webhook/manifests.yaml

Justification:
getting rid of
```
* spec.containers: Forbidden: pod updates may not add or remove containers
```
error
I tested in on deployment and editing the pod template is creating new replicaSet and new Pod with annotation change

fix: remove update operation from pod from mutatingWebhookConfigurations

---

sidecar/Dockerfile

Reverts SumoLogic/tailing-sidecar#441

Revert "build(deps): bump fluent/fluent-bit from 1.9.9 to 2.0.8 in /sidecar"

---

.github/workflows/release_builds.yml

Fixes:
```
shell: /usr/bin/bash -e {0}
env:
SIDECAR_IMAGE: ghcr.io/sumologic/tailing-sidecar
OPERATOR_IMAGE: ghcr.io/sumologic/tailing-sidecar-operator
LATEST_TAG: latest
docker buildx build \
--push \
--platform linux/amd64,linux/arm/v7,linux/arm64 \
--tag ghcr.io/sumologic/tailing-sidecar:0.5.6 \
.
ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

chore: fix release workflow

---

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml

following problem is now observed in workflow:
```
Invalid workflow file: .github/workflows/dev_builds.yml#L13The workflow is not valid. .github/workflows/dev_builds.yml (Line: 13, Col: 22): Unrecognized named-value: 'env'. Located at position 1 within expression: env.ECR_URL .github/workflows/dev_builds.yml (Line: 14, Col: 23): Unrecognized named-value: 'env'. Located at position 1 within expression: env.ECR_URL
--
[Invalid workflow file: .github/workflows/dev_builds.yml#L13](https://github.com/SumoLogic/tailing-sidecar/actions/runs/4489527193/workflow)
The workflow is not valid. .github/workflows/dev_builds.yml (Line: 13, Col: 22): Unrecognized named-value: 'env'. Located at position 1 within expression: env.ECR_URL .github/workflows/dev_builds.yml (Line: 14, Col: 23): Unrecognized …
```

fix(ci): fix pushing images to container registry

---

.github/workflows/pull_requests.yml

Don't really want to spend time on investigating this issue, but seems that using the same cluster name may be the reason of failing tests

chore: use different cluster names for gh actions

---

helm/tailing-sidecar-operator/Chart.yaml

Changes:
- bb331ab build(deps): bump golang from 1.20.1 to 1.20.2 in /sidecar
- e6d2e7d build(deps): bump golang from 1.20.2 to 1.20.3 in /sidecar
- ea06443 build(deps): bump fluent/fluent-bit from 1.9.9 to 2.0.10 in /sidecar
Using minor version because of fluentd upgrade from 1.x.x to 2.y.y

chore: prepare v0.7.0

---

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml

remove set-output based on https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix deprecations in github actions

---

operator/Dockerfile
operator/Makefile
operator/config.go
operator/config_test.go
operator/go.mod
operator/main.go

Adds support for configuration file for Tailing Sidecar Operator
This is first implementation step for #467
Configuration file will be mounted in helm chart using `configMap` (in next PR).
`configMap` will make it easier to config Sidecar container (`image`, `commands`, `configuuration`, `resources`)

feat(operator): add support for configuration file

---

helm/tailing-sidecar-operator/conf/operator.yaml
helm/tailing-sidecar-operator/templates/_helpers.tpl
helm/tailing-sidecar-operator/templates/configmap.yaml
helm/tailing-sidecar-operator/templates/resources.yaml

Use configmap in helm chart to provide configuration for sidecar operator.
This is another step for https://github.com/SumoLogic/tailing-sidecar/pull/467
The last step will be adding `customConfigmap` (content or name), which will be injected into sidecar, which is going to allow to override fluent-bit configuration

feat(helm): use configmap to configure tailing-sidecar-operator

---

helm/tailing-sidecar-operator/conf/operator.yaml
helm/tailing-sidecar-operator/templates/resources.yaml
helm/tailing-sidecar-operator/values.yaml
operator/config.go
operator/config_test.go
operator/main.go

The same as https://github.com/operator-framework/operator-sdk/issues/1813#issuecomment-733513350, I encounter `leader election lost`. 
We can increasing the `LeaseDuration`, `RenewDeadline ` and `RetryPeriod` like [opentelemetry-operator](https://github.com/open-telemetry/opentelemetry-operator/blob/a8653601cd6a6e2b35fd7f3e1a28b4e9608fb794/main.go#L181)

support config leader election

---

.github/workflows/pull_requests.yml
CHANGELOG.md
helm/tailing-sidecar-operator/Chart.yaml

Cut off new release which should resolve the following issues:
- https://github.com/SumoLogic/tailing-sidecar/issues/30
- https://github.com/SumoLogic/tailing-sidecar/issues/226
`CHANGELOG`:
- build(deps): bump fluent/fluent-bit from 2.0.10 to 2.0.11 in /sidecar [#512]
- build(deps): bump golang from 1.20.3 to 1.20.5 in /sidecar [#521] [#538]
- build(deps): bump golang from 1.20.3 to 1.20.5 in /operator [#520] [#539]
- feat(operator): add support for configuration file [#470]
- feat(helm): use configmap to configure tailing-sidecar-operator [#534]
- chore(sidecar): use debian bookworm for package base [#553]
- feat(operator): support config sidecar pod resources [#552]
- feat(operator): support config leader election [#550]
- feat(operator): allow to override sidecar configuration [#551] …

chore: prepare release v0.8.0

---

sidecar/Dockerfile
sidecar/out_gstdout/go.mod
sidecar/out_gstdout/go.sum

Update fluent-bit in order to mitigate medium and high severities:
before:
```
✗ Low severity vulnerability found in systemd/libsystemd0
Description: Authentication Bypass
Info: https://security.snyk.io/vuln/SNYK-DEBIAN11-SYSTEMD-1291054
Introduced through: systemd/libsystemd0@252.5-2~bpo11+1
From: systemd/libsystemd0@252.5-2~bpo11+1
✗ Low severity vulnerability found in systemd/libsystemd0
Description: Link Following
Info: https://security.snyk.io/vuln/SNYK-DEBIAN11-SYSTEMD-524969
Introduced through: systemd/libsystemd0@252.5-2~bpo11+1
From: systemd/libsystemd0@252.5-2~bpo11+1
✗ Low severity vulnerability found in systemd/libsystemd0
Description: Improper Validation of Integrity Check Value
Info: https://security.snyk.io/vuln/SNYK-DEBIAN11-SYSTEMD-5733387
Introduced through: …
```

chore(sidecar): update fluent-bit to 2.1.7

---

.gitignore
tests/modified/operator/daemonset-with-annotations/00-assert.yaml
tests/modified/operator/deployment-with-annotations/00-assert.yaml
tests/modified/operator/deployment-with-annotations/01-assert.yaml
tests/modified/operator/pod-with-annotations/00-assert.yaml
tests/modified/operator/pod-with-annotations/01-assert.yaml
tests/modified/operator/pod-with-cr/00-assert.yaml
tests/modified/operator/pod-with-cr/01-assert.yaml
tests/modified/operator/statefulset-with-annotations/00-assert.yaml
tests/operator/daemonset-with-annotations/00-assert.yaml
tests/operator/deployment-with-annotations/00-assert.yaml
tests/operator/deployment-with-annotations/01-assert.yaml
tests/operator/pod-with-annotations/00-assert.yaml
tests/operator/pod-with-annotations/01-assert.yaml
tests/operator/pod-with-cr/00-assert.yaml
tests/operator/pod-with-cr/01-assert.yaml
tests/operator/statefulset-with-annotations/00-assert.yaml
tests/sidecar/pod-with-sidecar/00-assert.yaml

See https://github.com/SumoLogic/tailing-sidecar/pull/600 for a demonstration.

test: show operator logs on e2e test failure

---

kind.yaml

We should define which versions we support and run tests on the oldest and latest. For now though, just latest is fine.

ci: upgrade e2e k8s version to 1.27

---

Makefile
helm/tailing-sidecar-operator/templates/resources.yaml
kuttl-test-helm-certmanager.yaml
kuttl-test-helm-custom-configuration.yaml
kuttl-test-helm.yaml
kuttl-test.yaml
operator/config/default/manager_webhook_patch.yaml
operator/main.go

Use dedicated controller-runtime facilities to create health and readiness checks for the webhook server.
Unfortunately it seems like this doesn't solve the webhook unavailability issue right after starting the operator. I've added an explicit 10 second wait to the E2E tests for now, we'll have to see if that's enough to fix the problem.

feat(operator): add proper health checks

---

sidecar/otelcol/.gitignore
sidecar/otelcol/.goreleaser.yaml
sidecar/otelcol/.otelcol-builder.yaml
sidecar/otelcol/Dockerfile
sidecar/otelcol/Makefile
sidecar/otelcol/config.yaml

Add the build infrastructure for a sidecar using Otelcol. This isn't used anywhere yet, and only allows the sidecar to be built locally. We use otelcolbuilder and goreleaser, plus a Makefile to manage them.

feat: add experimental otelcol sidecar

---

.github/workflows/dev_builds.yml

For the otelcol sidecar, we actually need the tag to be semver compliant, so the dev version needs to include the previous git tag. This means that we also need to fetch tags when checking out the repository.

ci: fix otelcol sidecar dev build

---

.github/workflows/dev_builds.yml

I'd like to avoid a full clone here, so I'm going to try a treeless clone instead. See https://github.com/actions/checkout/issues/1152 for reference.

ci: use a treeless git clone for otel sidecar dev builds

---

Makefile
helm/tests/values.withCertManager.yaml
helm/tests/values.withFluentBitCustomConfiguration.yaml
helm/tests/values.withOtelcolCustomConfiguration.yaml
helm/tests/values.yaml
kuttl-test-helm-certmanager.yaml
kuttl-test-helm-fluentbit-custom-configuration.yaml
kuttl-test-helm-otelcol-custom-configuration.yaml
kuttl-test-helm.yaml
kuttl-test.yaml

chore: rename sidecar image in tests to not indicate that the image is related to fluentbit and otelcol

chore: rename sidecar image in tests

---

CHANGELOG.md
helm/tailing-sidecar-operator/Chart.yaml

- feat: build ubi images [#654]
- add affinity config for operator pod [#670]
- build(deps): bump Fluent Bit from 2.2.2 to 3.0.0 [#672]

chore: prepare release v0.11.0

---

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml
operator/Makefile
sidecar/fluentbit/Makefile

```
preflight check container ghcr.io/sumologic/tailing-sidecar-operator:3cf903d-ubi --platform=linux/arm64
time="2024-06-03T14:10:14+02:00" level=info msg="certification library version" version="1.9.6 <commit: 354d10d9af8b5a64c7c2230a6656186957c3ed9f>"
time="2024-06-03T14:10:14+02:00" level=info msg="running checks for ghcr.io/sumologic/tailing-sidecar-operator:3cf903d-ubi for platform linux/arm64"
time="2024-06-03T14:10:14+02:00" level=info msg="target image" image="ghcr.io/sumologic/tailing-sidecar-operator:3cf903d-ubi"
time="2024-06-03T14:10:20+02:00" level=info msg="check completed" check=HasLicense result=PASSED
time="2024-06-03T14:10:20+02:00" level=info msg="check completed" check=HasUniqueTag result=PASSED
time="2024-06-03T14:10:20+02:00" level=info msg="check completed" …
```

chore: set version and release_number labels in ubi image

---

.github/workflows/dev_builds.yml
.github/workflows/pull_requests.yml
.github/workflows/release_builds.yml
operator/Makefile
operator/go.mod

This should unblock #707.
I've also upgraded controller-tools, as it paniced when compiled with Go 1.22.

deps(operator): bump go to 1.22

---

helm/tailing-sidecar-operator/values.yaml
operator/config/default/manager_auth_proxy_patch.yaml

This fixes CVE-2023-45288 and CVE-2022-21698.

deps: upgrade kube-rbac-proxy to v0.18.0

---

.github/workflows/dev_builds.yml
.github/workflows/pull_requests.yml

fix: Remove otel builds until we upgrade it to the latest version
This PR could be reverted, once we successfully upgrade the otel sidecar to the latest version.

fix: Remove otel builds until we upgrade it to the latest version

---

sidecar/fluentbit/Dockerfile
sidecar/fluentbit/Dockerfile.ubi
sidecar/fluentbit/docker-bake.hcl

Updates the fluentbit images to Go 1.24.5 and adds a Docker Bake file to simplify building & testing locally.

Update Go to 1.24.5 for fluentbit images
